/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef p4_api_CONSTANTS_H
#define p4_api_CONSTANTS_H

#include "p4_api_types.h"

namespace p4_thrift {

class p4_apiConstants {
 public:
  p4_apiConstants();

};

extern const p4_apiConstants g_p4_api_constants;

} // namespace

#endif
