/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "p4_api_constants.h"

namespace p4_thrift {

const p4_apiConstants g_p4_api_constants;

p4_apiConstants::p4_apiConstants() {
}

} // namespace

